// Generated by CoffeeScript 1.10.0

/*
 * Created by Nickolay on 24.12.2015.
 */

(function() {
  var filter;

  filter = function(messages, rules) {
    var escapeRegExpExceptStarAndQuestion, from_match, i, j, key, len, len1, message, replaceQuestion, replaceStar, result, rule, to_match;
    escapeRegExpExceptStarAndQuestion = /[\-\[\]\/\{\}\(\)\+\.\\\^\$\|]/g;
    replaceStar = /\*/g;
    replaceQuestion = /\?/g;
    for (i = 0, len = rules.length; i < len; i++) {
      rule = rules[i];
      if (rule.from != null) {
        rule.from_regexp = new RegExp("^" + rule.from.replace(escapeRegExpExceptStarAndQuestion, "\\$&").replace(replaceStar, '.*').replace(replaceQuestion, '.') + "$");
      }
      if (rule.to != null) {
        rule.to_regexp = new RegExp("^" + rule.to.replace(escapeRegExpExceptStarAndQuestion, "\\$&").replace(replaceStar, '.*').replace(replaceQuestion, '.') + "$");
      }
    }
    result = {};
    for (key in messages) {
      message = messages[key];
      result[key] = [];
      for (j = 0, len1 = rules.length; j < len1; j++) {
        rule = rules[j];
        if (rule.action == null) {
          continue;
        }
        from_match = rule.from != null ? rule.from_regexp.test(message.from) : true;
        if (!from_match) {
          continue;
        }
        to_match = rule.to != null ? rule.to_regexp.test(message.to) : true;
        if (!to_match) {
          continue;
        }
        result[key].push(rule.action);
      }
    }
    return result;
  };

  module.exports = {
    filter: filter
  };

}).call(this);

//# sourceMappingURL=filter.js.map
