// Generated by CoffeeScript 1.4.0
(function() {
  var MailUtility;

  MailUtility = (function() {

    function MailUtility() {}

    MailUtility.prototype.filter = function(messages, roles) {
      var filteredMessages, index, key, messageActions, regExpFrom, regExpTo, value;
      filteredMessages = {};
      for (key in messages) {
        value = messages[key];
        messageActions = [];
        for (index in roles) {
          regExpFrom = new RegExp('');
          regExpTo = new RegExp('');
          if (roles[index]['from']) {
            regExpFrom = new RegExp(roles[index]['from'].replace('*', '.*').replace('?', '.?'));
          }
          if (roles[index]['to']) {
            regExpTo = new RegExp(roles[index]['to'].replace('*', '.*').replace('?', '.?'));
          }
          if (regExpFrom.exec(value['from']) !== null && regExpTo.exec(value['to']) !== null) {
            messageActions.push(roles[index]['action']);
          }
        }
        if (messageActions.length > 0) {
          filteredMessages[key] = messageActions;
        }
      }
      return filteredMessages;
    };

    return MailUtility;

  })();

  exports.filter = new MailUtility().filter;

}).call(this);
